<?php
    // [TODO]
    $cLang = array(
        "languageD" => "LOLCAT",

        // [categories]
        "recentC" => "MOST RESENT ON FULPTUBE - WORLDWIDE PLZ?",
        "musicC" => "MUSIC",
        "reccomendedC" => "RECOMMENDD",
        "videoC" => "GAMIN",
        // [video]
        "byUsr" => "BAI",
        "agoLeft" => "A FEW",
        "agoRight" => "", // <agoLeft> <date> <agoRight> ex: 3 seconds ago
        "justNow" => "JUS NAO",
        "ago" => "AGO",
        "country" => "COUNTRY",
        "eViews" => "VIEWZ",
        "worldwide" => "WORLDWIDE",
        "gotIt" => "GETED IT :D",
        "welcomeToFulpTubeHomepage" => "WELCOM 2 TEH FULPTUBE HOMEPAGE",
        // [sidebar]
        "channelsForYou" => "CHANNELS 4 U",
        "dashboardText" => "VIDEOS FRUM UR CHANNEL SUBSCRIPSHUNS AN PERSONALIZD VIDEO RECOMMENDASHUNS APPEAR BELOW. FULPTUBE SORTS THEES VIDEOS BASD ON WUT WE FINKZ ULL WANTS 2 WATCH NEXT.<br><br>
        WANTS 2 C ALL TEH LATEST ACTIVITY FRUM UR SUBSCRIPSHUNS?<br>
        CHECK OUT <A HREF=\"#\">MAH SUBSCRIPSHUNS</A>.",
        "subscriptions" => "SUBSCRIPSHUNS",
        "subscriptionManage" => "MANAGE SUBSCRIPSHUNS",
        "browseChannels" => "BROWSE CHANNELZ",
        "newestVideos" => "NEWEST VIDEOZ",
        "signInNow" => "SIGN IN NAO 2 C UR CHANNELS AN RECOMMENDASHUNS!",
        // [header]
        "uploadVid" => "UPLOAD",
        "browse" => "BROWSE",
        "vChannel" => "CHANNEL",
        "feed" => "FEED",
        "vUploaded" => "UPLOADED",
        "vCancel" => "CANCEL",
        "vDuration" => "DURASHUN",
        "annoHowtoTitle" => "HOW 2 USE:",
        "videoResponseStart" => "<a href=\"/videoresponse?v=",
        "videoResponseEnd" => "\">CREATE VIDEO RESPONSE</a> or ",
        "vViews" => "VIEWS",
        "vLikes" => "LIKES",
        "annoCreator" => "ANNOTASHUN MAKR BY CRAZY FROG",
        "vDislikes" => "DISLIKES",
        "toCreateAnnotations" => "2 START CREATIN ANNOTASHUNS 4 UR VIDEO, PLZ UPLOAD FILE.",
        "vStatus" => "Status",
        "toggleCommenting" => "Toggle Commenting",
        "vComments" => "Comments",
        "annoHowto" => 'SET TEH POSISHUN, SCALE, COLOR AN DURASHUN 4 UR ANNOTASHUNS.<BR><BR>
        PRES TEH "ADD 2 OUTPUT" BUTN 2 SAVE UR CHANGEZ.<BR><BR>
        IF U DON\T LIEK TEH CHANGEZ U MADE, PRES TEH "UNDO" BUTN.<BR><BR>
        2 START NEW, PRES TEH "CLEAR OUTPUT" BUTN.<BR><BR>
        IF U R HAPPEH WIF UR ANNOTASHUNS, PRES TEH "COPY 2 CLIPBORD" BUTN 2 COPY TEH FINISHD CONTENTS 2 UR CLIPBORD.',
        "vURL" => "VIDEO URL",
        "actualUploadVideo" => "UPLOAD VIDEO",
        "delete" => "DELET",
        "thumbnail" => "THUMBNAIL",
        "upload" => "UPLOAD",
        "signIn" => "SIGN IN",
        // [time]
        "year" => "year",
        "month" => "month",
        "week" => "week",
        "day" => "day",
        "hour" => "hour",
        "minute" => "minute",
        "second" => "second",

        "pluralTimeRight" => "s",
        // [watch page]
        "subscribe" => "Subscribe",
        "language" => "Language",
        "copyright" => "Copyright",
        "about" => "About",
        "shareVid" => "Share",
        "addTo" => "Add to",
        "tags" => "Tags",
        "thumbnail" => "Thumbnail",
        "charremaining" => "characters remaining",
        "rectag" => "Recommended tags",
        "vidStatistics" => "Statistics",
        "showMore" => "Show More",
        "prePost" => "unused, do not translate",
        "post" => "post",
        "cPost" => "Post",
        "showLess" => "Show Less",
        "reply" => "Reply",
        "shareyourthoughts" => "Share your thoughts",
        "allComments" => "All Comments",
        "publishedAt2" => "Published at",
        "topComments" => "Top Comments",
        "loadMore" => "Load More",
        // [profile]
        "discussion" => "Discussion",
        "recentUploads" => "Recent Uploads",
        "playlists" => "Playlists",
        "profilePic" => "Profile Picture",
        "uploadBanner" => "Upload Banner",
        "uploadImage" => "Upload Image",
        "joined" => "Account created at",
        "messageProfile" => "Message",
        "uploadedAVideo" => "uploaded a video",
        "subscribers" => "subscribers",
        "userJoined" => "Joined at %d",
        "featuredChannel" => "Featured Channels",
        "popularChannels" => "Popular Channels",
        "theseRecommendations" => "These recommendations have been automatically generated by FulpTube.",
        // [inbox]
        "newComment" => "New comment",
        "newSubscriber" => "New subscriber",
        "inbox" => "Inbox",
        "markAll" => "Mark all as Read",
        "compose" => "Compose",
        "from" => "From:",
        "sent" => "Sent",
        "sendMessage" => "Send Message",
        "date" => "Date",
        "to" => "To:",
        "subject" => "Subject:",
        "messageInbox" => "Message:",
        // [upload]
        "uTitle" => "Title",
        "category" => "Category",
        "privacySetting" => "Privacy Settings",
        "description" => "Description",
        // [sign in]
        "signInBenifits" => "Sign in now, and use your FulpTube account to: ",
        "s1a" => "Keep up with your favorite channels",
        "s1b" => "Save videos to watch later, watch recommendations just for you, or subscribe to get updates from your favorite channels.",
        "s2a" => "Watch everywhere",
        "s2b" => "Take your picks with you wherever you go ? watch on your smartphone, tablet, or smart TV.",
        "s3a" => "Share with your friends",
        "s3b" => "See videos shared by your friends across all your social networks ? all in one place.",
        // [misc]
        //"" => "",
        "username2" => "Username",
        "password2" => "Password",
        "email2" => "E-Mail",
        "confirmpw2" => "Confirm Password",
        "register" => "Register",
        "signUp" => "Sign Up",
        "orRegister" => "...or <a href='/newsignup'>register</a>",
        "unsubscribe" => "Unsubscribe",
        "addChannels" => "Add channels",
        "subscribed" => "Subscribed",
        "xVideos" => "videos",
        "uVideos" => "Videos",
        "transcribe" => "Transcribe",
        "statistics" => "Statistics",
        "report" => "Report",
        "popularChannels" => "Popular Channels on FulpTube",
        "featuredChannels" => "Featured Channels",
        "dateAddedoldNew" => "Date added (oldest - newest)",
        "dateAddedNewOld" => "Date added (newest - oldest)",
        "Uplaylist" => "Playlists",
        "mostPopular" => "Most Popular",
        "privacy" => "Privacy",
        "playlist" => "playlist",
        "termsAndCond" => "Terms",
        "sendFeedback" => "Send feedback",
        "recentUploads" => "Recent Uploads",
        "uploads" => "Upload",
        "searchSubscriptions" => "Search subscriptions",
        "comments" => "comment(s)",
        "inboxComments" => "Comments",
        "contactNotifications" => "Contact Notifications",
        "message" => "Message",
        "time" => "Time:",
        "joindate" => "Joined in ",
        "myChannel" => "My channel",
        "videoManager" => "Video Manager",
        "fulptubeSettings" => "Settings",
        "userSettings" => "User Settings",
        "signOut" => "Sign out",
        "foogleAccount" => "Foogle Account",
        "thisisyou" => "This is you.",
        "overview" => "Overview",
        "name" => "Name",
        "password" => "Password",
        "changePW" => "Change password",
        "cemail" => "You will be sent a password reset confirmation E-Mail.",
        "misc" => "Misc",
        "accCreated" => "Account creation:",
        "loginDate" => "Last Login:",
        "customization" => "Customization",
        "personalMessages" => "Personal Messages",
        "sharedWithYou" => "Shared with You",
        "banner" => "Banner",
        "resWarn" => "Note: The optimal banner resolution is 821x176. Anything higher-lower res will be stretched to fit properly.",
        "yourPhoto" => "Tu foto",
        "socialLinks" => "Enlaces de Sociales",
        "links" => "Links",
        "customURL" => "Custom URL",
        "leaveBlank" => "Leave blank if you don't want to set these.",
        "featureAndDescribe" => "Feature and Describe",
        "describeAndfeature" => "Describe and Feature",
        "sent" => "Sent",
        "webVTT" => "Note: Only WebVTT is supported.",
        "edit" => "Edit",
        "maxRes" => "Note: Max size is 1080p.",
        "bio" => "Bio",
        "captionsNotWorking" => "Captions are temporarily not working currently.",
        "anno" => "Annotations",
        "basicInfo" => "Basic Info",
        "videoManager" => "Video Manager",
        "displayName" => "Display Name",
        "addMoreVideos" => "Add more videos",
        "featuredChannels" => "Featured Channels",
        "exampleFeaturedChannels" => "Seperate by commas. Do not add spaces next to the commas. Example: chief bazinga,Sniped,Joel98",
        "featuredVideo" => "Featured Video",
        "warningFeaturedVideo" => "Must not have extra whitespace/spaces at the end. Example: MTYwNTQ4ODc4Mja=24 is valid. DO NOT INCLUDE THE FULPTUBE.ROCKS LINK, JUST THE ID",
        "toggleFlash" => "Toggle Flash Player",
        "aboutResults" => "About %s results",
        "searchSubscriptions" => "Search subscriptions",
        "watchLater" => "Watch Later",
        "donotreupload" => "                            <B STYLE=\"FONT-SIZE: 18PX;\">PLZ, DOAN REUPLOAD VIDEOS DAT ARENT YOURS.</B><BR>
        <BR>
        THUMBNAILS R AUTO GENERATD. <BR>
        ALL VIDEOS R CONVERTD 2 720P@1000KBPS H264/AAC BY FFMPEG, ALLOWIN WIDE VARIETY OV FORMATS.<BR>
        VIDEOS MUST BE SMALLR THAN 100MB. (CUZ OV CLOUDFLARE)<BR>
        NO COPYRIGHTD CONTENT DAT WILL GIT US DMCAD.<BR>
        <B>VIDEOS R MANUALLY APPROVD.</B>",
        "watchHistory" => "History",
        "whatToWatch" => "What to Watch",
        "mySubscriptions" => "My Subscriptions",
        "analytics" => "Analytics",
        "dashboard" => "Dashboard",
        "adobeStatus" => "Adobe Flash no est? ",
        "active" => "activated",
        "guide" => 'Guide',
        "deactive" => "deactivated",

        "fulptubeTOS" => "FulpTube Terms and Service",
        "fulptubeTOSSub" => "                                                <B>GENERAL RULEZ</B><BR>
        JUS DOAN BE HUGE IDIOT. DIS AR TEH SIET MADE 4 FUN. <BR>
        DIS AR TEH SIET AIMD TOWARDZ RECREATIN 2013 YOUTUBE. <BR>
        TEH PLAYERS + JS OV TEH SIET IZ OWND BY YOUTUBE. IT NOT OURS.<BR>
        FULPTUBE IZ NOT ASSOCIATD IN ANY WAI WIF GOOGLE LLC.<BR>
        ALL CONTENT FINDZ VIOLATIN TEH USAS LAWS AN FEDERAL REGULASHUNS WILL BE REMOVD AN TEH AKOWNT ASSOCIATD WIF IT BANND.<BR>
        ALL ATTEMPTS AT BAN EVASHUN WILL NOT BE TOLERATD AN WILL END UP WIF BAN FRUM FULPTUBE.<BR>
        NO NSFW, NO BIGOTRY, NO HOMOFOBIA, AN JUS USE COMMON SENSE. THX.<BR><BR>
        <B>BUG REPORTS + VIDEO REPORTS</B><BR>
        IF U C VIDEO BREAKIN TEH TOS, PLZ NOTIFY US AT TEH DISCORD IN DA FOOTR.<BR>
        FINDZ BUG? REPORT IT IN DA #BUG-REPORTS CHANNEL IN DA DISCORD.<BR><BR>
        <B>CONTACT</B><BR>
        Email: spacemygithub@gmail.com<br>
        Official Discord Server: In the footer<br>
        Discord: bhief cazinga#5644",

        "ftPrivacy" => "FulpTube Privacy Policy ",
        "ftPrivacySubtext" => "                        <b>Privacy</b><br>
        We do NOT store IPs. All that is stored is your password, email, and username.<br>
        Other things that are stored are your videos, comments, etcettera. You can request to retrieve them.<br>
        We do not sell data. <br>
        Have any privacy concerns? The discord is located above.<br>",

        "ftCopyright" => "FulpTube Copyright",
        "ftCopyrightSubtext" => "                                                <B>COPYRIGHT</B><BR>
        MAK SURE URE NOT MAKIN MONEY OFF OV MUSIC DAT IZ PLAYIN IN VIDEOS BAKGROUND.<BR>
        U CAN UPLOAD RAW FULL SONGS AS LONG AS U GIV TEH ORIGINAL PUBLISHR CREDIT.<BR>
        IMPERSONASHUN OV OTHR TRADEMARKD OR COPYRIGHTD COMPANIEZ IZ NOT TOLERATD.<BR>
        U HAS 2 MAK IT EASILY NOTICEABLE DAT UR CHANNEL IZ PARODY IF IT IZ.",
        "ftQA" => "FulpTube Q&A",

        "ftQASubtext" => "                        <B>I FORGOT MAH PASWORD.</B><BR>
        JOIN TEH DISCORD 4 SUPPORT REGARDIN PASWORDZ.<BR><BR>
        <B>Y?</B><BR>
        I MADE FULPTUBE AS PROJECT 4 FUN AN I NEVR EXPECTD SO MUTCH TRACSHUN AN ATTENSHUN 4 IT. <BR>IM KEEPIN DIS SIET UP AS LONG AS I CAN.<BR>U SHUD JOIN TEH DISCORD IF U WANTS 2 TALK 2 TEH COMMUNITY.<BR><BR>
        <B>HOOS TEH OWNR OV DIS SIET?</B><BR>
        <A HREF=\"/USR?N=CHIEF%20BAZINGA\">CHIEF BAZINGA</A><BR>",
    );
?>
