<?php
    // [TODO]
    $cLang = array(
        "languageD" => "English",

        // [categories]
        "recentC" => "Most Recent on FulpTube - Worldwide",
        "musicC" => "Music",
        "reccomendedC" => "Recommended",
        "videoC" => "Gaming",
        // [video] 
        "byUsr" => "by",
        "agoLeft" => "a few",
        "agoRight" => "", // <agoLeft> <date> <agoRight> ex: 3 seconds ago
        "justNow" => "just now",
        "ago" => "ago",
        "country" => "Country",
        "eViews" => "views",
        "worldwide" => "Worldwide",
        "gotIt" => "Got it!",
        "welcomeToFulpTubeHomepage" => "Welcome to the FulpTube homepage",
        // [sidebar]
        "channelsForYou" => "Channels for You",
        "dashboardText" => "Videos from your channel subscriptions and personalized video recommendations appear below. FulpTube sorts these videos based on what we think you'll want to watch next.<br><br>
        Want to see all the latest activity from your subscriptions?<br>
        Check out <a href=\"#\">My Subscriptions</a>.",
        "subscriptions" => "Subscriptions",
        "subscriptionManage" => "Manage Subscriptions",
        "browseChannels" => "Browse Channels",
        "newestVideos" => "Newest Videos",
        "signInNow" => "Sign in now to see your channels and recommendations!",
        // [header]
        "uploadVid" => "Upload",
        "browse" => "Browse",
        "vChannel" => "Channel",
        "feed" => "Feed",
        "vUploaded" => "Uploaded",
        "vCancel" => "Cancel",
        "vDuration" => "Duration",
        "annoHowtoTitle" => "How to use:",
        "videoResponseStart" => "<a href=\"/videoresponse?v=",
        "videoResponseEnd" => "\">Create a video response</a> or ",
        "vViews" => "views",
        "vLikes" => "Likes",
        "annoCreator" => "Annotation Maker by Crazy Frog",
        "vDislikes" => "Dislikes",
        "toCreateAnnotations" => "To start creating annotations for your video, please upload a file.",
        "vStatus" => "Status",
        "toggleCommenting" => "Toggle Commenting",
        "vComments" => "Comments",
        "annoHowto" => 'Set the position, scale, color and duration for your annotations.<br><br>
        Press the "Add to Output" button to save your changes.<br><br>
        If you don\'t like the changes you made, press the "Undo" button.<br><br>
        To start new, press the "Clear Output" button.<br><br>
        If you are happy with your annotations, press the "Copy to Clipboard" button to copy the finished contents to your clipboard.',
        "vURL" => "Video URL",
        "actualUploadVideo" => "Upload Video",
        "delete" => "Delete",
        "thumbnail" => "Thumbnail",
        "upload" => "Upload",
        "signIn" => "Sign in",
        // [time]
        "year" => "year",
        "month" => "month",
        "week" => "week",
        "day" => "day",
        "hour" => "hour",
        "minute" => "minute",
        "second" => "second",

        "pluralTimeRight" => "s",
        // [watch page]
        "subscribe" => "Subscribe",
        "language" => "Language",
        "copyright" => "Copyright",
        "about" => "About",
        "shareVid" => "Share",
        "addTo" => "Add to",
        "tags" => "Tags",
        "thumbnail" => "Thumbnail",
        "charremaining" => "characters remaining",
        "rectag" => "Recommended tags",
        "vidStatistics" => "Statistics",
        "showMore" => "Show More",
        "prePost" => "unused, do not translate",
        "post" => "post",
        "cPost" => "Post",
        "showLess" => "Show Less",
        "reply" => "Reply",
        "shareyourthoughts" => "Share your thoughts",
        "allComments" => "All Comments",
        "publishedAt2" => "Published at",
        "topComments" => "Top Comments",
        "loadMore" => "Load More",
        // [profile]
        "discussion" => "Discussion",
        "recentUploads" => "Recent Uploads",
        "playlists" => "Playlists",
        "profilePic" => "Profile Picture",
        "uploadBanner" => "Upload Banner",
        "uploadImage" => "Upload Image",
        "joined" => "Account created at",
        "messageProfile" => "Message",
        "uploadedAVideo" => "uploaded a video",
        "subscribers" => "subscribers",
        "userJoined" => "Joined at %d",
        "featuredChannel" => "Featured Channels",
        "popularChannels" => "Popular Channels",
        "theseRecommendations" => "These recommendations have been automatically generated by FulpTube.",
        // [inbox]
        "newComment" => "New comment",
        "newSubscriber" => "New subscriber",
        "inbox" => "Inbox",
        "markAll" => "Mark all as Read",
        "compose" => "Compose",
        "from" => "From:",
        "sent" => "Sent",
        "sendMessage" => "Send Message",
        "date" => "Date",
        "to" => "To:",
        "subject" => "Subject:",
        "messageInbox" => "Message:",
        // [upload]
        "uTitle" => "Title",
        "category" => "Category",
        "privacySetting" => "Privacy Settings",
        "description" => "Description",
        // [sign in]
        "signInBenifits" => "Sign in now, and use your FulpTube account to: ",
        "s1a" => "Keep up with your favorite channels",
        "s1b" => "Save videos to watch later, watch recommendations just for you, or subscribe to get updates from your favorite channels.",
        "s2a" => "Watch everywhere", 
        "s2b" => "Take your picks with you wherever you go ? watch on your smartphone, tablet, or smart TV.",
        "s3a" => "Share with your friends",
        "s3b" => "See videos shared by your friends across all your social networks ? all in one place.", 
        // [misc]
        //"" => "",
        "username2" => "Username",
        "password2" => "Password",
        "email2" => "E-Mail",
        "confirmpw2" => "Confirm Password",
        "register" => "Register",
        "signUp" => "Sign Up",
        "orRegister" => "...or <a href='/newsignup'>register</a>",
        "unsubscribe" => "Unsubscribe",
        "addChannels" => "Add channels",
        "subscribed" => "Subscribed",
        "xVideos" => "videos",
        "uVideos" => "Videos",
        "transcribe" => "Transcribe",
        "statistics" => "Statistics",
        "report" => "Report",
        "popularChannels" => "Popular Channels on FulpTube",
        "featuredChannels" => "Featured Channels",
        "dateAddedoldNew" => "Date added (oldest - newest)",
        "dateAddedNewOld" => "Date added (newest - oldest)",
        "Uplaylist" => "Playlists",
        "mostPopular" => "Most Popular",
        "privacy" => "Privacy",
        "playlist" => "playlist",
        "termsAndCond" => "Terms",
        "sendFeedback" => "Send feedback",
        "recentUploads" => "Recent Uploads",
        "uploads" => "Upload",
        "searchSubscriptions" => "Search subscriptions",
        "comments" => "comment(s)",
        "inboxComments" => "Comments",
        "contactNotifications" => "Contact Notifications",
        "message" => "Message",
        "time" => "Time:",
        "joindate" => "Joined in ",
        "myChannel" => "My channel",
        "videoManager" => "Video Manager",
        "fulptubeSettings" => "Settings",
        "userSettings" => "User Settings",
        "signOut" => "Sign out",
        "foogleAccount" => "Foogle Account",
        "thisisyou" => "This is you.",
        "overview" => "Overview",
        "name" => "Name",
        "password" => "Password",
        "changePW" => "Change password",
        "cemail" => "You will be sent a password reset confirmation E-Mail.",
        "misc" => "Misc",
        "accCreated" => "Account creation:",
        "loginDate" => "Last Login:",
        "customization" => "Customization",
        "personalMessages" => "Personal Messages",
        "sharedWithYou" => "Shared with You",
        "banner" => "Banner",
        "resWarn" => "Note: The optimal banner resolution is 821x176. Anything higher-lower res will be stretched to fit properly.",
        "yourPhoto" => "Tu foto",
        "socialLinks" => "Enlaces de Sociales",
        "links" => "Links",
        "customURL" => "Custom URL",
        "leaveBlank" => "Leave blank if you don't want to set these.",
        "featureAndDescribe" => "Feature and Describe",
        "describeAndfeature" => "Describe and Feature",
        "sent" => "Sent",
        "webVTT" => "Note: Only WebVTT is supported.",
        "edit" => "Edit",
        "maxRes" => "Note: Max size is 1080p.",
        "bio" => "Bio",
        "captionsNotWorking" => "Captions are temporarily not working currently.",
        "anno" => "Annotations",
        "basicInfo" => "Basic Info",
        "videoManager" => "Video Manager",
        "displayName" => "Display Name",
        "addMoreVideos" => "Add more videos",
        "featuredChannels" => "Featured Channels",
        "exampleFeaturedChannels" => "Seperate by commas. Do not add spaces next to the commas. Example: chief bazinga,Sniped,Joel98",
        "featuredVideo" => "Featured Video",
        "warningFeaturedVideo" => "Must not have extra whitespace/spaces at the end. Example: MTYwNTQ4ODc4Mja=24 is valid. DO NOT INCLUDE THE FULPTUBE.ROCKS LINK, JUST THE ID",
        "toggleFlash" => "Toggle Flash Player",
        "aboutResults" => "About %s results",
        "searchSubscriptions" => "Search subscriptions",
        "watchLater" => "Watch Later",
        "donotreupload" => "                            <b style=\"font-size: 18px;\">Please, don't reupload videos that aren't yours.</b><br>
        <br>
        Thumbnails are auto generated. <br>
        All videos are converted to 720p@1000kbps H264/AAC by FFMPEG, allowing a wide variety of formats.<br>
        Videos must be smaller than 100MB. (because of Cloudflare)<br>
        No copyrighted content that will get us DMCA'd.<br>
        <b>Videos are manually approved.</b>",
        "watchHistory" => "History",
        "whatToWatch" => "What to Watch",
        "mySubscriptions" => "My Subscriptions",
        "analytics" => "Analytics",
        "dashboard" => "Dashboard",
        "adobeStatus" => "Adobe Flash no est? ",
        "active" => "activated",
        "guide" => 'Guide',
        "deactive" => "deactivated",

        "fulptubeTOS" => "FulpTube Terms and Service",
        "fulptubeTOSSub" => "                                                <b>General Rules</b><br>
        Just don't be a huge idiot. This is a site made for fun. <br>
        This is a site aimed towards recreating 2013 YouTube. <br>
        The players + JS of the site is owned by YouTube. It is not ours.<br>
        FulpTube is not associated in any way with Google LLC.<br>
        All content found violating the USA's laws and federal regulations will be removed and the account associated with it banned.<br>
        All attempts at ban evasion will NOT BE TOLERATED and will end up with a ban from FulpTube.<br>
        No NSFW, no bigotry, no homophobia, and just use common sense. Thanks.<br><br>
        <b>Bug Reports + Video Reports</b><br>
        If you see a video breaking the TOS, please notify us at the discord in the footer.<br>
        Found a bug? report it in the #bug-reports channel in the discord.<br><br>
        <b>Contact</b><br>
        Email: spacemygithub@gmail.com<br>
        Official Discord Server: In the footer<br>
        Discord: bhief cazinga#5644",

        "ftPrivacy" => "FulpTube Privacy Policy ",
        "ftPrivacySubtext" => "                        <b>Privacy</b><br>
        We do NOT store IPs. All that is stored is your password, email, and username.<br>
        Other things that are stored are your videos, comments, etcettera. You can request to retrieve them.<br>
        We do not sell data. <br>
        Have any privacy concerns? The discord is located above.<br>",
        
        "ftCopyright" => "FulpTube Copyright",
        "ftCopyrightSubtext" => "                                                <b>Copyright</b><br>
        Make sure you're not making money off of music that is playing in a video's background.<br>
        You can upload raw full songs as long as you give the original publisher credit.<br>
        Impersonation of other trademarked or copyrighted companies is not tolerated.<br>
        You have to make it easily noticeable that your channel is a parody if it is.",
        "ftQA" => "FulpTube Q&A",
    
        "ftQASubtext" => "                        <b>I forgot my password.</b><br>
        Join the Discord for support regarding passwords.<br><br>
        <b>Why?</b><br>
        I made FulpTube as a project for fun and I never expected so much traction and attention for it. <br>I'm keeping this site up as long as I can.<br>You should join the Discord if you want to talk to the community.<br><br>
        <b>Who's the owner of this site?</b><br>
        <a href=\"/user?n=chief%20bazinga\">chief bazinga</a><br>",
    );
?>
